run:
  timeout: 5m
  tests: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: todo-app
  govet:
    check-shadowing: true
  errcheck:
    check-type-assertions: true
  gosimple:
    go: "1.21"
  staticcheck:
    go: "1.21"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck